### ISSUE TITLE
Required usage of auto_route

### ISSUE THREAD

**Issue by webnickell** [purplenoodlesoop/purple-starter#102]
Why is auto_route package required? I suppose, that would be better, when this project just use Navigator 2.0 approach without any of third party packages.

**Comment by purplenoodlesoop** [comment]
The starter is opinionated. 

In my experience, `auto_route` provided the most pleasant experience of Router + Navigator 2.0 usage compared to `go_router` and other solutions, including hand-crafted ones.

If `auto_route` is not a good fit for your purposes – you can replace it in your project created from the starter.
