### ISSUE TITLE
Add @nonVirtual to build method

### ISSUE THREAD

**Issue by webnickell** [purplenoodlesoop/purple-starter#103]
There is comment before ScopeDelegate implementation
```dart
/// instead of the [build] method. Class that extends [ScopeDelegate] should
/// **NEVER OVERRIDE THE BUILD METHOD**. It will break things.
abstract class ScopeDelegate<S extends Scope> extends State<S> {
```
But you can add @nonVirtual annotation from meta/meta.dart, and linter will prompt programmer that he can't override it

**Comment by purplenoodlesoop** [comment]
Closed via #126. Thanks for the issue!
