### ISSUE TITLE
Remove android  & ios folders from the repository

### ISSUE THREAD

**Issue by zs-dima** [purplenoodlesoop/purple-starter#28]
Could be nice to remove android  & ios folders from the repository.
Android, ios, web, windows and etc folders could be created by the flutter create command.
So user will have actual content version for the certain framework version and only folders needed for the user project.

**Comment by purplenoodlesoop** [comment]
You are very right. Thanks!

**Comment by purplenoodlesoop** [comment]
Closed via #29
