### ISSUE TITLE
Makefile platform issues

### ISSUE THREAD

**Issue by zs-dima** [purplenoodlesoop/purple-starter#46]
Could be nice to make Makefile multi-platform

Currently Windows fire exceptions for the time and rm commands:

`time : The term 'time' is not recognized as the name of a cmdlet, function, script file, or operable program`

```
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf build .flutter-plugins .flutter-plugins-dependencies coverage  ...
```

**Comment by purplenoodlesoop** [comment]
Fixed by #110
