### ISSUE TITLE
Environment Scope

### ISSUE THREAD

**Issue by zs-dima** [purplenoodlesoop/purple-starter#54]
Could be nice to add Environment Scope - default and loaded from the environment variables.

`final env = const String.fromEnvironment('env', defaultValue: '').toLowerCase();`

**Comment by purplenoodlesoop** [comment]
Closed by #57. Thanks for the issues!

**Comment by purplenoodlesoop** [comment]
Reopened to add the environment `env` variable getter

**Comment by zs-dima** [comment]
@purplenoodlesoop 
Could be nice to app enum or predefined environments:
```
Development
Environment
Production
Staging
```

**Comment by purplenoodlesoop** [comment]
Closed again by #58
