### ISSUE TITLE
Reorganize App Scopes

### ISSUE THREAD

**Issue by zs-dima** [purplenoodlesoop/purple-starter#61]
Could be nice to reorganize App Scopes

1.
DependenciesScope(child: RepositoryScope( - all this scopes data quite internal and could be nice to hide it from the below levels.
For example they could be joined into AppScope that will share only interfaces that could be visible below.

Could be nice to organize Scopes in more structured way, for example:
RootRestorationScope(restorationId: 'id', child:
  AppEnvironmentScope(
    child: AppInitScope(
      child: AppAuthScope(
        child: AppScope(
          child: AppRouterScope(),
- without unneeded DependenciesScope.of(context).database visible everywhere and etc

2.
Could be nice to place *Scope.dart in one place instead spread them into feature, core... folders

**Comment by purplenoodlesoop** [comment]
Closed by #119
